#
# Azure Pipelines configuration for building and testing react on Linux, Windows, and macOS.
#

trigger:
- master

jobs:
- job: Lint
  displayName: 'Lint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - template: .azure-pipelines/common/setup.yml
    - bash: echo $(Build.SourceBranchName)
      displayName: 'Run lint'

  variables:
    AZURE_PIPELINES_BRANCH: $(Build.SourceBranchName)
    CI: true
    CI_PULL_REQUEST: eq( $(Build.Reason), 'PullRequest')
    REPO_SLUG:  $(Build.Repository.Name)
