#
# Azure Pipelines configuration for building and testing react on Linux, Windows, and macOS.
#

trigger:
- master

jobs:
- job: Lint
  displayName: 'Lint'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
    - bash: echo $(Build.SourceBranchName)
    - bash: echo $CI_PULL_REQUEST
    - bash: echo $AZURE_PIPELINES_BRANCH

  variables:
    AZURE_PIPELINES_BRANCH: $(Build.SourceBranchName)
    CI: true
    CI_PULL_REQUEST: eq( $(Build.Reason), 'PullRequest')
    REPO_SLUG:  $(Build.Repository.Name)
