#
# Azure Pipelines configuration for running tests and other checks on Linux/macOS.
#

steps:
  - script: node ./scripts/prettier/index
    displayName: 'Prettier'

  - bash: echo $REPO_SLUG

  - script: node ./scripts/tasks/flow-ci
    displayName: 'Flow CI'

  - bash: echo $REPO_SLUG

  - script: |
      export JEST_JUNIT_OUTPUT=.azure-pipelines/test-results/test-basic-linux.xml
      yarn test --maxWorkers=2
    displayName: 'Run tests'

  - script: ./scripts/circleci/check_license.sh
    displayName: 'Check license'

  - script: ./scripts/circleci/check_modules.sh
    displayName: 'Check modules'

  - script: ./scripts/circleci/test_print_warnings.sh
    displayName: 'Test print warnings'

  - bash: echo $REPO_SLUG

  - script: ./scripts/circleci/check_license.sh
    displayName: 'Check license'

  - bash: echo $REPO_SLUG

  - script: ./scripts/circleci/check_modules.sh
    displayName: 'Check modules'

  - bash: echo $REPO_SLUG

  - script: ./scripts/circleci/test_print_warnings.sh
    displayName: 'Test print warnings'

  - bash: echo $REPO_SLUG

  # TODO: Need to set up connection with GitHub and env vars. for this to work
  - script: ./scripts/circleci/track_stats.sh
    displayName: 'Track stats'

  - task: PublishTestResults@2
    inputs:
      testRunTitle: 'Linux: Basic'
      testResultsFormat: 'JUnit'
      testResultsFiles: '.azure-pipelines/test-results/test-basic-linux.xml'
    displayName: 'Publish test results to Azure Pipelines'
    condition: succeededOrFailed()
